setblock ~-10 ~23 ~ minecraft:white_wool
setblock ~-9 ~23 ~ minecraft:orange_wool
setblock ~-8 ~23 ~ minecraft:magenta_wool
setblock ~-7 ~23 ~ minecraft:light_blue_wool
setblock ~-6 ~23 ~ minecraft:yellow_wool
setblock ~-5 ~23 ~ minecraft:lime_wool
setblock ~-4 ~23 ~ minecraft:pink_wool
setblock ~-3 ~23 ~ minecraft:gray_wool
setblock ~-2 ~23 ~ minecraft:light_gray_wool
setblock ~-1 ~23 ~ minecraft:cyan_wool
setblock ~0 ~23 ~ minecraft:purple_wool
setblock ~1 ~23 ~ minecraft:blue_wool
setblock ~2 ~23 ~ minecraft:brown_wool
setblock ~3 ~23 ~ minecraft:green_wool
setblock ~4 ~23 ~ minecraft:red_wool
setblock ~5 ~23 ~ minecraft:black_wool
setblock ~6 ~23 ~ minecraft:white_wool
setblock ~7 ~23 ~ minecraft:orange_wool
setblock ~8 ~23 ~ minecraft:magenta_wool
setblock ~9 ~23 ~ minecraft:light_blue_wool
setblock ~-10 ~22 ~ minecraft:yellow_wool
setblock ~-9 ~22 ~ minecraft:lime_wool
setblock ~-8 ~22 ~ minecraft:pink_wool
setblock ~-7 ~22 ~ minecraft:gray_wool
setblock ~-6 ~22 ~ minecraft:light_gray_wool
setblock ~-5 ~22 ~ minecraft:cyan_wool
setblock ~-4 ~22 ~ minecraft:purple_wool
setblock ~-3 ~22 ~ minecraft:blue_wool
setblock ~-2 ~22 ~ minecraft:brown_wool
setblock ~-1 ~22 ~ minecraft:green_wool
setblock ~0 ~22 ~ minecraft:red_wool
setblock ~1 ~22 ~ minecraft:black_wool
setblock ~2 ~22 ~ minecraft:white_wool
setblock ~3 ~22 ~ minecraft:orange_wool
setblock ~4 ~22 ~ minecraft:magenta_wool
setblock ~5 ~22 ~ minecraft:light_blue_wool
setblock ~6 ~22 ~ minecraft:yellow_wool
setblock ~7 ~22 ~ minecraft:lime_wool
setblock ~8 ~22 ~ minecraft:pink_wool
setblock ~9 ~22 ~ minecraft:gray_wool
setblock ~-10 ~21 ~ minecraft:light_gray_wool
setblock ~-9 ~21 ~ minecraft:cyan_wool
setblock ~-8 ~21 ~ minecraft:purple_wool
setblock ~-7 ~21 ~ minecraft:blue_wool
setblock ~-6 ~21 ~ minecraft:brown_wool
setblock ~-5 ~21 ~ minecraft:green_wool
setblock ~-4 ~21 ~ minecraft:red_wool
setblock ~-3 ~21 ~ minecraft:black_wool
setblock ~-2 ~21 ~ minecraft:white_wool
setblock ~-1 ~21 ~ minecraft:orange_wool
setblock ~0 ~21 ~ minecraft:magenta_wool
setblock ~1 ~21 ~ minecraft:light_blue_wool
setblock ~2 ~21 ~ minecraft:yellow_wool
setblock ~3 ~21 ~ minecraft:lime_wool
setblock ~4 ~21 ~ minecraft:pink_wool
setblock ~5 ~21 ~ minecraft:gray_wool
setblock ~6 ~21 ~ minecraft:light_gray_wool
setblock ~7 ~21 ~ minecraft:cyan_wool
setblock ~8 ~21 ~ minecraft:purple_wool
setblock ~9 ~21 ~ minecraft:blue_wool
setblock ~-10 ~20 ~ minecraft:brown_wool
setblock ~-9 ~20 ~ minecraft:green_wool
setblock ~-8 ~20 ~ minecraft:red_wool
setblock ~-7 ~20 ~ minecraft:black_wool
setblock ~-6 ~20 ~ minecraft:white_wool
setblock ~-5 ~20 ~ minecraft:orange_wool
setblock ~-4 ~20 ~ minecraft:magenta_wool
setblock ~-3 ~20 ~ minecraft:light_blue_wool
setblock ~-2 ~20 ~ minecraft:yellow_wool
setblock ~-1 ~20 ~ minecraft:lime_wool
setblock ~0 ~20 ~ minecraft:pink_wool
setblock ~1 ~20 ~ minecraft:gray_wool
setblock ~2 ~20 ~ minecraft:light_gray_wool
setblock ~3 ~20 ~ minecraft:cyan_wool
setblock ~4 ~20 ~ minecraft:purple_wool
setblock ~5 ~20 ~ minecraft:blue_wool
setblock ~6 ~20 ~ minecraft:brown_wool
setblock ~7 ~20 ~ minecraft:green_wool
setblock ~8 ~20 ~ minecraft:red_wool
setblock ~9 ~20 ~ minecraft:black_wool
setblock ~-10 ~19 ~ minecraft:white_wool
setblock ~-9 ~19 ~ minecraft:orange_wool
setblock ~-8 ~19 ~ minecraft:magenta_wool
setblock ~-7 ~19 ~ minecraft:light_blue_wool
setblock ~-6 ~19 ~ minecraft:yellow_wool
setblock ~-5 ~19 ~ minecraft:lime_wool
setblock ~-4 ~19 ~ minecraft:pink_wool
setblock ~-3 ~19 ~ minecraft:gray_wool
setblock ~-2 ~19 ~ minecraft:light_gray_wool
setblock ~-1 ~19 ~ minecraft:cyan_wool
setblock ~0 ~19 ~ minecraft:purple_wool
setblock ~1 ~19 ~ minecraft:blue_wool
setblock ~2 ~19 ~ minecraft:brown_wool
setblock ~3 ~19 ~ minecraft:green_wool
setblock ~4 ~19 ~ minecraft:red_wool
setblock ~5 ~19 ~ minecraft:black_wool
setblock ~6 ~19 ~ minecraft:white_wool
setblock ~7 ~19 ~ minecraft:orange_wool
setblock ~8 ~19 ~ minecraft:magenta_wool
setblock ~9 ~19 ~ minecraft:light_blue_wool
setblock ~-10 ~18 ~ minecraft:yellow_wool
setblock ~-9 ~18 ~ minecraft:lime_wool
setblock ~-8 ~18 ~ minecraft:pink_wool
setblock ~-7 ~18 ~ minecraft:gray_wool
setblock ~-6 ~18 ~ minecraft:light_gray_wool
setblock ~-5 ~18 ~ minecraft:cyan_wool
setblock ~-4 ~18 ~ minecraft:purple_wool
setblock ~-3 ~18 ~ minecraft:blue_wool
setblock ~-2 ~18 ~ minecraft:brown_wool
setblock ~-1 ~18 ~ minecraft:green_wool
setblock ~0 ~18 ~ minecraft:red_wool
setblock ~1 ~18 ~ minecraft:black_wool
setblock ~2 ~18 ~ minecraft:white_wool
setblock ~3 ~18 ~ minecraft:orange_wool
setblock ~4 ~18 ~ minecraft:magenta_wool
setblock ~5 ~18 ~ minecraft:light_blue_wool
setblock ~6 ~18 ~ minecraft:yellow_wool
setblock ~7 ~18 ~ minecraft:lime_wool
setblock ~8 ~18 ~ minecraft:pink_wool
setblock ~9 ~18 ~ minecraft:gray_wool
setblock ~-10 ~17 ~ minecraft:light_gray_wool
setblock ~-9 ~17 ~ minecraft:cyan_wool
setblock ~-8 ~17 ~ minecraft:purple_wool
setblock ~-7 ~17 ~ minecraft:blue_wool
setblock ~-6 ~17 ~ minecraft:brown_wool
setblock ~-5 ~17 ~ minecraft:green_wool
setblock ~-4 ~17 ~ minecraft:red_wool
setblock ~-3 ~17 ~ minecraft:black_wool
setblock ~-2 ~17 ~ minecraft:white_wool
setblock ~-1 ~17 ~ minecraft:orange_wool
setblock ~0 ~17 ~ minecraft:magenta_wool
setblock ~1 ~17 ~ minecraft:light_blue_wool
setblock ~2 ~17 ~ minecraft:yellow_wool
setblock ~3 ~17 ~ minecraft:lime_wool
setblock ~4 ~17 ~ minecraft:pink_wool
setblock ~5 ~17 ~ minecraft:gray_wool
setblock ~6 ~17 ~ minecraft:light_gray_wool
setblock ~7 ~17 ~ minecraft:cyan_wool
setblock ~8 ~17 ~ minecraft:purple_wool
setblock ~9 ~17 ~ minecraft:blue_wool
setblock ~-10 ~16 ~ minecraft:brown_wool
setblock ~-9 ~16 ~ minecraft:green_wool
setblock ~-8 ~16 ~ minecraft:red_wool
setblock ~-7 ~16 ~ minecraft:black_wool
setblock ~-6 ~16 ~ minecraft:white_wool
setblock ~-5 ~16 ~ minecraft:orange_wool
setblock ~-4 ~16 ~ minecraft:magenta_wool
setblock ~-3 ~16 ~ minecraft:light_blue_wool
setblock ~-2 ~16 ~ minecraft:yellow_wool
setblock ~-1 ~16 ~ minecraft:lime_wool
setblock ~0 ~16 ~ minecraft:pink_wool
setblock ~1 ~16 ~ minecraft:gray_wool
setblock ~2 ~16 ~ minecraft:light_gray_wool
setblock ~3 ~16 ~ minecraft:cyan_wool
setblock ~4 ~16 ~ minecraft:purple_wool
setblock ~5 ~16 ~ minecraft:blue_wool
setblock ~6 ~16 ~ minecraft:brown_wool
setblock ~7 ~16 ~ minecraft:green_wool
setblock ~8 ~16 ~ minecraft:red_wool
setblock ~9 ~16 ~ minecraft:black_wool
setblock ~-10 ~15 ~ minecraft:white_wool
setblock ~-9 ~15 ~ minecraft:orange_wool
setblock ~-8 ~15 ~ minecraft:magenta_wool
setblock ~-7 ~15 ~ minecraft:light_blue_wool
setblock ~-6 ~15 ~ minecraft:yellow_wool
setblock ~-5 ~15 ~ minecraft:lime_wool
setblock ~-4 ~15 ~ minecraft:pink_wool
setblock ~-3 ~15 ~ minecraft:gray_wool
setblock ~-2 ~15 ~ minecraft:light_gray_wool
setblock ~-1 ~15 ~ minecraft:cyan_wool
setblock ~0 ~15 ~ minecraft:purple_wool
setblock ~1 ~15 ~ minecraft:blue_wool
setblock ~2 ~15 ~ minecraft:brown_wool
setblock ~3 ~15 ~ minecraft:green_wool
setblock ~4 ~15 ~ minecraft:red_wool
setblock ~5 ~15 ~ minecraft:black_wool
setblock ~6 ~15 ~ minecraft:white_wool
setblock ~7 ~15 ~ minecraft:orange_wool
setblock ~8 ~15 ~ minecraft:magenta_wool
setblock ~9 ~15 ~ minecraft:light_blue_wool
setblock ~-10 ~14 ~ minecraft:yellow_wool
setblock ~-9 ~14 ~ minecraft:lime_wool
setblock ~-8 ~14 ~ minecraft:pink_wool
setblock ~-7 ~14 ~ minecraft:gray_wool
setblock ~-6 ~14 ~ minecraft:light_gray_wool
setblock ~-5 ~14 ~ minecraft:cyan_wool
setblock ~-4 ~14 ~ minecraft:purple_wool
setblock ~-3 ~14 ~ minecraft:blue_wool
setblock ~-2 ~14 ~ minecraft:brown_wool
setblock ~-1 ~14 ~ minecraft:green_wool
setblock ~0 ~14 ~ minecraft:red_wool
setblock ~1 ~14 ~ minecraft:black_wool
setblock ~2 ~14 ~ minecraft:white_wool
setblock ~3 ~14 ~ minecraft:orange_wool
setblock ~4 ~14 ~ minecraft:magenta_wool
setblock ~5 ~14 ~ minecraft:light_blue_wool
setblock ~6 ~14 ~ minecraft:yellow_wool
setblock ~7 ~14 ~ minecraft:lime_wool
setblock ~8 ~14 ~ minecraft:pink_wool
setblock ~9 ~14 ~ minecraft:gray_wool
setblock ~-10 ~13 ~ minecraft:light_gray_wool
setblock ~-9 ~13 ~ minecraft:cyan_wool
setblock ~-8 ~13 ~ minecraft:purple_wool
setblock ~-7 ~13 ~ minecraft:blue_wool
setblock ~-6 ~13 ~ minecraft:brown_wool
setblock ~-5 ~13 ~ minecraft:green_wool
setblock ~-4 ~13 ~ minecraft:red_wool
setblock ~-3 ~13 ~ minecraft:black_wool
setblock ~-2 ~13 ~ minecraft:white_wool
setblock ~-1 ~13 ~ minecraft:orange_wool
setblock ~0 ~13 ~ minecraft:magenta_wool
setblock ~1 ~13 ~ minecraft:light_blue_wool
setblock ~2 ~13 ~ minecraft:yellow_wool
setblock ~3 ~13 ~ minecraft:lime_wool
setblock ~4 ~13 ~ minecraft:pink_wool
setblock ~5 ~13 ~ minecraft:gray_wool
setblock ~6 ~13 ~ minecraft:light_gray_wool
setblock ~7 ~13 ~ minecraft:cyan_wool
setblock ~8 ~13 ~ minecraft:purple_wool
setblock ~9 ~13 ~ minecraft:blue_wool
setblock ~-10 ~12 ~ minecraft:brown_wool
setblock ~-9 ~12 ~ minecraft:green_wool
setblock ~-8 ~12 ~ minecraft:red_wool
setblock ~-7 ~12 ~ minecraft:black_wool
setblock ~-6 ~12 ~ minecraft:white_wool
setblock ~-5 ~12 ~ minecraft:orange_wool
setblock ~-4 ~12 ~ minecraft:magenta_wool
setblock ~-3 ~12 ~ minecraft:light_blue_wool
setblock ~-2 ~12 ~ minecraft:yellow_wool
setblock ~-1 ~12 ~ minecraft:lime_wool
setblock ~0 ~12 ~ minecraft:pink_wool
setblock ~1 ~12 ~ minecraft:gray_wool
setblock ~2 ~12 ~ minecraft:light_gray_wool
setblock ~3 ~12 ~ minecraft:cyan_wool
setblock ~4 ~12 ~ minecraft:purple_wool
setblock ~5 ~12 ~ minecraft:blue_wool
setblock ~6 ~12 ~ minecraft:brown_wool
setblock ~7 ~12 ~ minecraft:green_wool
setblock ~8 ~12 ~ minecraft:red_wool
setblock ~9 ~12 ~ minecraft:black_wool
setblock ~-10 ~11 ~ minecraft:white_wool
setblock ~-9 ~11 ~ minecraft:orange_wool
setblock ~-8 ~11 ~ minecraft:magenta_wool
setblock ~-7 ~11 ~ minecraft:light_blue_wool
setblock ~-6 ~11 ~ minecraft:yellow_wool
setblock ~-5 ~11 ~ minecraft:lime_wool
setblock ~-4 ~11 ~ minecraft:pink_wool
setblock ~-3 ~11 ~ minecraft:gray_wool
setblock ~-2 ~11 ~ minecraft:light_gray_wool
setblock ~-1 ~11 ~ minecraft:cyan_wool
setblock ~0 ~11 ~ minecraft:purple_wool
setblock ~1 ~11 ~ minecraft:blue_wool
setblock ~2 ~11 ~ minecraft:brown_wool
setblock ~3 ~11 ~ minecraft:green_wool
setblock ~4 ~11 ~ minecraft:red_wool
setblock ~5 ~11 ~ minecraft:black_wool
setblock ~6 ~11 ~ minecraft:white_wool
setblock ~7 ~11 ~ minecraft:orange_wool
setblock ~8 ~11 ~ minecraft:magenta_wool
setblock ~9 ~11 ~ minecraft:light_blue_wool
setblock ~-10 ~10 ~ minecraft:yellow_wool
setblock ~-9 ~10 ~ minecraft:lime_wool
setblock ~-8 ~10 ~ minecraft:pink_wool
setblock ~-7 ~10 ~ minecraft:gray_wool
setblock ~-6 ~10 ~ minecraft:light_gray_wool
setblock ~-5 ~10 ~ minecraft:cyan_wool
setblock ~-4 ~10 ~ minecraft:purple_wool
setblock ~-3 ~10 ~ minecraft:blue_wool
setblock ~-2 ~10 ~ minecraft:brown_wool
setblock ~-1 ~10 ~ minecraft:green_wool
setblock ~0 ~10 ~ minecraft:red_wool
setblock ~1 ~10 ~ minecraft:black_wool
setblock ~2 ~10 ~ minecraft:white_wool
setblock ~3 ~10 ~ minecraft:orange_wool
setblock ~4 ~10 ~ minecraft:magenta_wool
setblock ~5 ~10 ~ minecraft:light_blue_wool
setblock ~6 ~10 ~ minecraft:yellow_wool
setblock ~7 ~10 ~ minecraft:lime_wool
setblock ~8 ~10 ~ minecraft:pink_wool
setblock ~9 ~10 ~ minecraft:gray_wool
setblock ~-10 ~9 ~ minecraft:light_gray_wool
setblock ~-9 ~9 ~ minecraft:cyan_wool
setblock ~-8 ~9 ~ minecraft:purple_wool
setblock ~-7 ~9 ~ minecraft:blue_wool
setblock ~-6 ~9 ~ minecraft:brown_wool
setblock ~-5 ~9 ~ minecraft:green_wool
setblock ~-4 ~9 ~ minecraft:red_wool
setblock ~-3 ~9 ~ minecraft:black_wool
setblock ~-2 ~9 ~ minecraft:white_wool
setblock ~-1 ~9 ~ minecraft:orange_wool
setblock ~0 ~9 ~ minecraft:magenta_wool
setblock ~1 ~9 ~ minecraft:light_blue_wool
setblock ~2 ~9 ~ minecraft:yellow_wool
setblock ~3 ~9 ~ minecraft:lime_wool
setblock ~4 ~9 ~ minecraft:pink_wool
setblock ~5 ~9 ~ minecraft:gray_wool
setblock ~6 ~9 ~ minecraft:light_gray_wool
setblock ~7 ~9 ~ minecraft:cyan_wool
setblock ~8 ~9 ~ minecraft:purple_wool
setblock ~9 ~9 ~ minecraft:blue_wool
setblock ~-10 ~8 ~ minecraft:brown_wool
setblock ~-9 ~8 ~ minecraft:green_wool
setblock ~-8 ~8 ~ minecraft:red_wool
setblock ~-7 ~8 ~ minecraft:black_wool
setblock ~-6 ~8 ~ minecraft:white_wool
setblock ~-5 ~8 ~ minecraft:orange_wool
setblock ~-4 ~8 ~ minecraft:magenta_wool
setblock ~-3 ~8 ~ minecraft:light_blue_wool
setblock ~-2 ~8 ~ minecraft:yellow_wool
setblock ~-1 ~8 ~ minecraft:lime_wool
setblock ~0 ~8 ~ minecraft:pink_wool
setblock ~1 ~8 ~ minecraft:gray_wool
setblock ~2 ~8 ~ minecraft:light_gray_wool
setblock ~3 ~8 ~ minecraft:cyan_wool
setblock ~4 ~8 ~ minecraft:purple_wool
setblock ~5 ~8 ~ minecraft:blue_wool
setblock ~6 ~8 ~ minecraft:brown_wool
setblock ~7 ~8 ~ minecraft:green_wool
setblock ~8 ~8 ~ minecraft:red_wool
setblock ~9 ~8 ~ minecraft:black_wool
setblock ~-10 ~7 ~ minecraft:white_wool
setblock ~-9 ~7 ~ minecraft:orange_wool
setblock ~-8 ~7 ~ minecraft:magenta_wool
setblock ~-7 ~7 ~ minecraft:light_blue_wool
setblock ~-6 ~7 ~ minecraft:yellow_wool
setblock ~-5 ~7 ~ minecraft:lime_wool
setblock ~-4 ~7 ~ minecraft:pink_wool
setblock ~-3 ~7 ~ minecraft:gray_wool
setblock ~-2 ~7 ~ minecraft:light_gray_wool
setblock ~-1 ~7 ~ minecraft:cyan_wool
setblock ~0 ~7 ~ minecraft:purple_wool
setblock ~1 ~7 ~ minecraft:blue_wool
setblock ~2 ~7 ~ minecraft:brown_wool
setblock ~3 ~7 ~ minecraft:green_wool
setblock ~4 ~7 ~ minecraft:red_wool
setblock ~5 ~7 ~ minecraft:black_wool
setblock ~6 ~7 ~ minecraft:white_wool
setblock ~7 ~7 ~ minecraft:orange_wool
setblock ~8 ~7 ~ minecraft:magenta_wool
setblock ~9 ~7 ~ minecraft:light_blue_wool
setblock ~-10 ~6 ~ minecraft:yellow_wool
setblock ~-9 ~6 ~ minecraft:lime_wool
setblock ~-8 ~6 ~ minecraft:pink_wool
setblock ~-7 ~6 ~ minecraft:gray_wool
setblock ~-6 ~6 ~ minecraft:light_gray_wool
setblock ~-5 ~6 ~ minecraft:cyan_wool
setblock ~-4 ~6 ~ minecraft:purple_wool
setblock ~-3 ~6 ~ minecraft:blue_wool
setblock ~-2 ~6 ~ minecraft:brown_wool
setblock ~-1 ~6 ~ minecraft:green_wool
setblock ~0 ~6 ~ minecraft:red_wool
setblock ~1 ~6 ~ minecraft:black_wool
setblock ~2 ~6 ~ minecraft:white_wool
setblock ~3 ~6 ~ minecraft:orange_wool
setblock ~4 ~6 ~ minecraft:magenta_wool
setblock ~5 ~6 ~ minecraft:light_blue_wool
setblock ~6 ~6 ~ minecraft:yellow_wool
setblock ~7 ~6 ~ minecraft:lime_wool
setblock ~8 ~6 ~ minecraft:pink_wool
setblock ~9 ~6 ~ minecraft:gray_wool
setblock ~-10 ~5 ~ minecraft:light_gray_wool
setblock ~-9 ~5 ~ minecraft:cyan_wool
setblock ~-8 ~5 ~ minecraft:purple_wool
setblock ~-7 ~5 ~ minecraft:blue_wool
setblock ~-6 ~5 ~ minecraft:brown_wool
setblock ~-5 ~5 ~ minecraft:green_wool
setblock ~-4 ~5 ~ minecraft:red_wool
setblock ~-3 ~5 ~ minecraft:black_wool
setblock ~-2 ~5 ~ minecraft:white_wool
setblock ~-1 ~5 ~ minecraft:orange_wool
setblock ~0 ~5 ~ minecraft:magenta_wool
setblock ~1 ~5 ~ minecraft:light_blue_wool
setblock ~2 ~5 ~ minecraft:yellow_wool
setblock ~3 ~5 ~ minecraft:lime_wool
setblock ~4 ~5 ~ minecraft:pink_wool
setblock ~5 ~5 ~ minecraft:gray_wool
setblock ~6 ~5 ~ minecraft:light_gray_wool
setblock ~7 ~5 ~ minecraft:cyan_wool
setblock ~8 ~5 ~ minecraft:purple_wool
setblock ~9 ~5 ~ minecraft:blue_wool
setblock ~-10 ~4 ~ minecraft:brown_wool
setblock ~-9 ~4 ~ minecraft:green_wool
setblock ~-8 ~4 ~ minecraft:red_wool
setblock ~-7 ~4 ~ minecraft:black_wool
setblock ~-6 ~4 ~ minecraft:white_wool
setblock ~-5 ~4 ~ minecraft:orange_wool
setblock ~-4 ~4 ~ minecraft:magenta_wool
setblock ~-3 ~4 ~ minecraft:light_blue_wool
setblock ~-2 ~4 ~ minecraft:yellow_wool
setblock ~-1 ~4 ~ minecraft:lime_wool
setblock ~0 ~4 ~ minecraft:pink_wool
setblock ~1 ~4 ~ minecraft:gray_wool
setblock ~2 ~4 ~ minecraft:light_gray_wool
setblock ~3 ~4 ~ minecraft:cyan_wool
setblock ~4 ~4 ~ minecraft:purple_wool
setblock ~5 ~4 ~ minecraft:blue_wool
setblock ~6 ~4 ~ minecraft:brown_wool
setblock ~7 ~4 ~ minecraft:green_wool
setblock ~8 ~4 ~ minecraft:red_wool
setblock ~9 ~4 ~ minecraft:black_wool
