setblock ~-5 ~13 ~ minecraft:white_wool
setblock ~-4 ~13 ~ minecraft:orange_wool
setblock ~-3 ~13 ~ minecraft:magenta_wool
setblock ~-2 ~13 ~ minecraft:light_blue_wool
setblock ~-1 ~13 ~ minecraft:yellow_wool
setblock ~0 ~13 ~ minecraft:lime_wool
setblock ~1 ~13 ~ minecraft:pink_wool
setblock ~2 ~13 ~ minecraft:gray_wool
setblock ~3 ~13 ~ minecraft:light_gray_wool
setblock ~4 ~13 ~ minecraft:cyan_wool
setblock ~-5 ~12 ~ minecraft:purple_wool
setblock ~-4 ~12 ~ minecraft:blue_wool
setblock ~-3 ~12 ~ minecraft:brown_wool
setblock ~-2 ~12 ~ minecraft:green_wool
setblock ~-1 ~12 ~ minecraft:red_wool
setblock ~0 ~12 ~ minecraft:black_wool
setblock ~1 ~12 ~ minecraft:white_wool
setblock ~2 ~12 ~ minecraft:orange_wool
setblock ~3 ~12 ~ minecraft:magenta_wool
setblock ~4 ~12 ~ minecraft:light_blue_wool
setblock ~-5 ~11 ~ minecraft:yellow_wool
setblock ~-4 ~11 ~ minecraft:lime_wool
setblock ~-3 ~11 ~ minecraft:pink_wool
setblock ~-2 ~11 ~ minecraft:gray_wool
setblock ~-1 ~11 ~ minecraft:light_gray_wool
setblock ~0 ~11 ~ minecraft:cyan_wool
setblock ~1 ~11 ~ minecraft:purple_wool
setblock ~2 ~11 ~ minecraft:blue_wool
setblock ~3 ~11 ~ minecraft:brown_wool
setblock ~4 ~11 ~ minecraft:green_wool
setblock ~-5 ~10 ~ minecraft:red_wool
setblock ~-4 ~10 ~ minecraft:black_wool
setblock ~-3 ~10 ~ minecraft:white_wool
setblock ~-2 ~10 ~ minecraft:orange_wool
setblock ~-1 ~10 ~ minecraft:magenta_wool
setblock ~0 ~10 ~ minecraft:light_blue_wool
setblock ~1 ~10 ~ minecraft:yellow_wool
setblock ~2 ~10 ~ minecraft:lime_wool
setblock ~3 ~10 ~ minecraft:pink_wool
setblock ~4 ~10 ~ minecraft:gray_wool
setblock ~-5 ~9 ~ minecraft:light_gray_wool
setblock ~-4 ~9 ~ minecraft:cyan_wool
setblock ~-3 ~9 ~ minecraft:purple_wool
setblock ~-2 ~9 ~ minecraft:blue_wool
setblock ~-1 ~9 ~ minecraft:brown_wool
setblock ~0 ~9 ~ minecraft:green_wool
setblock ~1 ~9 ~ minecraft:red_wool
setblock ~2 ~9 ~ minecraft:black_wool
setblock ~3 ~9 ~ minecraft:white_wool
setblock ~4 ~9 ~ minecraft:orange_wool
setblock ~-5 ~8 ~ minecraft:magenta_wool
setblock ~-4 ~8 ~ minecraft:light_blue_wool
setblock ~-3 ~8 ~ minecraft:yellow_wool
setblock ~-2 ~8 ~ minecraft:lime_wool
setblock ~-1 ~8 ~ minecraft:pink_wool
setblock ~0 ~8 ~ minecraft:gray_wool
setblock ~1 ~8 ~ minecraft:light_gray_wool
setblock ~2 ~8 ~ minecraft:cyan_wool
setblock ~3 ~8 ~ minecraft:purple_wool
setblock ~4 ~8 ~ minecraft:blue_wool
setblock ~-5 ~7 ~ minecraft:brown_wool
setblock ~-4 ~7 ~ minecraft:green_wool
setblock ~-3 ~7 ~ minecraft:red_wool
setblock ~-2 ~7 ~ minecraft:black_wool
setblock ~-1 ~7 ~ minecraft:white_wool
setblock ~0 ~7 ~ minecraft:orange_wool
setblock ~1 ~7 ~ minecraft:magenta_wool
setblock ~2 ~7 ~ minecraft:light_blue_wool
setblock ~3 ~7 ~ minecraft:yellow_wool
setblock ~4 ~7 ~ minecraft:lime_wool
setblock ~-5 ~6 ~ minecraft:pink_wool
setblock ~-4 ~6 ~ minecraft:gray_wool
setblock ~-3 ~6 ~ minecraft:light_gray_wool
setblock ~-2 ~6 ~ minecraft:cyan_wool
setblock ~-1 ~6 ~ minecraft:purple_wool
setblock ~0 ~6 ~ minecraft:blue_wool
setblock ~1 ~6 ~ minecraft:brown_wool
setblock ~2 ~6 ~ minecraft:green_wool
setblock ~3 ~6 ~ minecraft:red_wool
setblock ~4 ~6 ~ minecraft:black_wool
setblock ~-5 ~5 ~ minecraft:white_wool
setblock ~-4 ~5 ~ minecraft:orange_wool
setblock ~-3 ~5 ~ minecraft:magenta_wool
setblock ~-2 ~5 ~ minecraft:light_blue_wool
setblock ~-1 ~5 ~ minecraft:yellow_wool
setblock ~0 ~5 ~ minecraft:lime_wool
setblock ~1 ~5 ~ minecraft:pink_wool
setblock ~2 ~5 ~ minecraft:gray_wool
setblock ~3 ~5 ~ minecraft:light_gray_wool
setblock ~4 ~5 ~ minecraft:cyan_wool
setblock ~-5 ~4 ~ minecraft:purple_wool
setblock ~-4 ~4 ~ minecraft:blue_wool
setblock ~-3 ~4 ~ minecraft:brown_wool
setblock ~-2 ~4 ~ minecraft:green_wool
setblock ~-1 ~4 ~ minecraft:red_wool
setblock ~0 ~4 ~ minecraft:black_wool
setblock ~1 ~4 ~ minecraft:white_wool
setblock ~2 ~4 ~ minecraft:orange_wool
setblock ~3 ~4 ~ minecraft:magenta_wool
setblock ~4 ~4 ~ minecraft:light_blue_wool
